const dashboardValueLabels: Record<string, string> = {
  ADMIN: "الإدارة",
  PARTNER: "شريك تنفيذ",
  AMBASSADOR: "سفير",
  CLIENT: "عميل",
  USER: "مستخدم",
  APPLICATION: "طلب انضمام",
  PARTNER_APPLICATION: "طلب شراكة",
  REFERRAL: "إحالة",
  PROJECT: "مشروع",
  CLIENT_PROJECT: "مشروع عميل",
  PARTNER_PROJECT: "مشروع شريك",
  PROJECT_STAGE: "مرحلة مشروع",
  INVOICE: "فاتورة",
  REWARD: "مكافأة",
  ADMIN_USER: "عضو إدارة",
  AMBASSADOR_REWARD: "مكافأة سفير",
  AMBASSADOR_REWARD_LEVEL: "مستوى مكافآت السفراء",

  PENDING: "قيد الانتظار",
  ACTIVE: "فعال",
  SUSPENDED: "موقوف",
  REJECTED: "مرفوض",
  ACCEPTED: "مقبول",
  APPROVED: "معتمد",
  CANCELLED: "ملغى",
  EXPECTED: "متوقعة",
  EARNED: "مستحقة",
  PAID: "مدفوعة",
  DUE: "مستحقة",
  OVERDUE: "متأخرة",
  DRAFT: "مسودة",
  VERIFYING: "قيد التحقق",
  ON_HOLD: "معلّقة",
  NOT_ELIGIBLE: "غير مستحقة",

  NEW: "جديدة",
  CONTACTED: "تم التواصل",
  INTERESTED: "مهتم",
  AWAITING_RESPONSE: "بانتظار الرد",
  NOT_INTERESTED: "غير مهتم",
  CONVERTED: "تحولت إلى عميل",
  PENDING_REVIEW: "قيد المراجعة",
  CONVERTED_TO_CLIENT: "تحولت إلى عميل",
  IN_REVIEW: "قيد المراجعة",
  NEEDS_INFO: "يحتاج معلومات إضافية",

  PLANNING: "التخطيط",
  ASSIGNED: "تم الإسناد",
  NOT_STARTED: "لم تبدأ",
  IN_PROGRESS: "قيد التنفيذ",
  REVIEW: "قيد المراجعة",
  COMPLETED: "مكتمل",

  RECEIVED: "تم الاستلام",
  REVIEWED: "تمت المراجعة",
  NEEDS_MORE_INFO: "يحتاج استكمالًا",
  ARCHIVED: "مؤرشف",

  FIXED: "مبلغ ثابت",
  PERCENTAGE: "نسبة مئوية",
  STANDARD: "فاتورة",
  RETURN: "مرتجع",
  FULL_TIME: "متفرغ بالكامل",
  PART_TIME: "متفرغ جزئيًا",

  DIRECT: "إحالة مباشرة",
  MANUAL: "إدخال يدوي من الإدارة",
  POSITIVE: "إيجابية",
  SENSITIVE: "حساسة",
  NORMAL: "تعديلات عادية",

  PARTNER_APPLICATION_SUBMITTED: "تقديم طلب شراكة",
  PARTNER_REVIEW_STARTED: "بدء مراجعة طلب الشريك",
  PARTNER_INFO_REQUESTED: "طلب معلومات إضافية من الشريك",
  PARTNER_APPLICATION_ACCEPTED: "قبول طلب الشراكة",
  PARTNER_APPLICATION_REJECTED: "رفض طلب الشراكة",
  PARTNER_ACCOUNT_ACTIVATED: "تفعيل حساب الشريك",
  PARTNER_ACCOUNT_SUSPENDED: "إيقاف حساب الشريك",
  PARTNER_PROFILE_UPDATED: "تعديل بيانات الشريك",
  PARTNER_NOTE_ADDED: "إضافة ملاحظة إدارية للشريك",
  PARTNER_PROJECT_ASSIGNED: "إسناد مشروع إلى شريك",
  PROJECT_CREATED: "إنشاء مشروع",
  PROJECT_UPDATED: "تحديث المشروع",
  PROJECT_CANCELLED: "إلغاء المشروع وإيقاف مراحله المستقبلية",
  ADMIN_MEMBER_CREATED: "إنشاء حساب عضو إدارة",
  ADMIN_PERMISSIONS_UPDATED: "تعديل صلاحيات عضو الإدارة",
  ADMIN_ACCOUNT_SUSPENDED: "إيقاف حساب عضو الإدارة",
  ADMIN_ACCOUNT_ACTIVATED: "تفعيل حساب عضو الإدارة",
  ADMIN_PROFILE_UPDATED: "تعديل بيانات عضو الإدارة",
  AMBASSADOR_REWARD_RATE_LOCKED: "تثبيت نسبة مكافأة المشروع",
  AMBASSADOR_REWARD_STAGE_CREATED: "إنشاء مرحلة مكافأة",
  AMBASSADOR_REWARD_STAGE_UPDATED: "تحديث مرحلة مكافأة",
  AMBASSADOR_REWARD_EARNED: "اعتماد استحقاق مكافأة",
  AMBASSADOR_REWARD_PAID: "صرف مكافأة سفير",
  AMBASSADOR_REWARD_CANCELLED: "إلغاء مكافأة سفير",
  AMBASSADOR_REWARD_LEVEL_UPDATED: "تعديل مستوى مكافآت السفراء",
};

const dashboardFieldLabels: Record<string, string> = {
  id: "المعرّف",
  name: "الاسم",
  email: "البريد الإلكتروني",
  phone: "رقم الهاتف",
  title: "العنوان",
  status: "الحالة",
  type: "النوع",
  role: "الدور",
  source: "المصدر",
  action: "العملية",
  category: "التصنيف",
  partnerId: "معرّف الشريك",
  ambassadorId: "معرّف السفير",
  clientId: "معرّف العميل",
  projectId: "معرّف المشروع",
  projectStageId: "معرّف مرحلة المشروع",
  referralId: "معرّف الإحالة",
  applicationId: "معرّف الطلب",
  userId: "معرّف المستخدم",
  actorId: "معرّف منفذ العملية",
  entityId: "معرّف العنصر",
  entityType: "نوع العنصر",
  entityLabel: "اسم العنصر",
  reviewState: "حالة المراجعة",
  paymentStatus: "حالة الدفع",
  commissionStatus: "حالة العمولة",
  commissionType: "نوع العمولة",
  progress: "نسبة الإنجاز",
  rate: "النسبة",
  amount: "المبلغ",
  baseAmount: "المبلغ الأساسي",
  currency: "العملة",
  reason: "السبب",
  note: "الملاحظة",
  notes: "الملاحظات",
  adminNotes: "ملاحظات الإدارة",
  decisionNotes: "ملاحظات القرار",
  isActive: "الحساب فعال",
  active: "فعال",
  approved: "معتمد",
  permissions: "الصلاحيات",
  age: "العمر",
  educationLevel: "المستوى التعليمي",
  educationSpecialty: "التخصص التعليمي",
  specialty: "التخصص المهني",
  workAreas: "مجالات العمل",
  supportServices: "الخدمات المدعومة",
  experienceYears: "سنوات الخبرة",
  availabilityType: "نوع التفرغ",
  assignmentId: "معرّف الإسناد",
  partnerIds: "الشركاء المسند إليهم",
  cancelledFutureStages: "المراحل المستقبلية الملغاة",
  referralPosition: "ترتيب الإحالة الشهري",
  level: "المستوى",
  rewardId: "معرّف المكافأة",
  rewardStatus: "حالة المكافأة",
  approvedAt: "تاريخ الاعتماد",
  minSuccessfulReferrals: "الحد الأدنى للإحالات الناجحة",
  createdAt: "تاريخ الإنشاء",
  updatedAt: "تاريخ آخر تحديث",
  earnedAt: "تاريخ الاستحقاق",
  paidAt: "تاريخ الدفع",
  cancelledAt: "تاريخ الإلغاء",
  dueAt: "تاريخ الاستحقاق",
};

const dashboardErrorLabels: Record<string, string> = {
  INVALID: "البيانات المدخلة غير صالحة.",
  INVALID_APPLICATION: "طلب الانضمام غير صالح.",
  INVALID_COMMISSION: "بيانات العمولة غير صالحة.",
  INVALID_COMMISSION_STATUS: "حالة العمولة غير صالحة.",
  INVALID_CURRENCY: "العملة المحددة غير صالحة.",
  INVALID_DECISION: "القرار المحدد غير صالح.",
  INVALID_FIELDS: "تحقق من الحقول المدخلة.",
  INVALID_REFERRAL_CODE: "رمز الإحالة غير صالح.",
  INVALID_REQUEST: "الطلب غير صالح.",
  INVALID_ROLE: "نوع الحساب المحدد غير صالح.",
  INVALID_STATUS: "الحالة المحددة غير صالحة.",
  TEMP_PASSWORD_REQUIRED: "أدخل كلمة مرور مؤقتة من 10 أحرف على الأقل.",
  EMAIL_EXISTS: "يوجد حساب بهذا البريد الإلكتروني بالفعل.",
  PHONE_EXISTS: "يوجد حساب بهذا الرقم بالفعل.",
  PARTNER_ALREADY_EXISTS: "يوجد حساب شريك بهذه البيانات بالفعل.",
  PARTNER_APPLICATION_EXISTS: "يوجد طلب شراكة بهذه البيانات بالفعل.",
  ALREADY_DECIDED: "تم اتخاذ قرار سابق على هذا الطلب.",
  CONFLICTING_STATUSES: "الحالات المحددة متعارضة.",
  CONVERTED_STATUS_LOCKED: "لا يمكن تغيير حالة إحالة تحولت إلى عميل.",
  COMMISSION_AMOUNT_REQUIRED: "أدخل مبلغ العمولة.",
  COMMISSION_NOT_DUE: "لا يمكن تسجيل العمولة قبل استحقاقها.",
  COMMISSION_RATE_REQUIRED: "أدخل نسبة العمولة.",
  EMPTY_MESSAGE: "لا يمكن إرسال رسالة فارغة.",
  FILES_TOO_LARGE: "حجم الملفات يتجاوز الحد المسموح.",
  FINANCIAL_CONDITION_NOT_MET: "لم تتحقق شروط الاستحقاق المالي بعد.",
  IDENTITY_CONFLICT: "تتعارض بيانات البريد أو الهاتف مع حساب آخر.",
  NAME_TAKEN: "هذا الاسم مستخدم بالفعل.",
  NOTES_REQUIRED: "أدخل الملاحظات المطلوبة.",
  REQUIRED_FIELDS: "يرجى إكمال جميع الحقول المطلوبة.",
  PROFILE_REQUIRED: "يرجى إكمال الملف الشخصي أولًا.",
  REFERRAL_NOT_APPROVED: "يجب اعتماد الإحالة أولًا.",
  SELF_REGISTRATION_DISABLED: "التسجيل المباشر غير متاح لهذا النوع من الحسابات.",
  TOO_MANY_FILES: "عدد الملفات يتجاوز الحد المسموح.",
  UNSUPPORTED_FILE_TYPE: "نوع الملف غير مدعوم.",
  USE_CLIENT_CONVERSION: "استخدم إجراء تحويل الإحالة إلى عميل.",
  EMAIL_NOT_CONFIGURED: "خدمة البريد الإلكتروني غير مهيأة حاليًا.",
  EMAIL_SEND_FAILED: "تعذر إرسال البريد الإلكتروني.",
  PHONE_MATCH_REQUIRES_CONFIRMATION: "رقم الهاتف مستخدم في حساب آخر ويحتاج إلى تأكيد.",
  UNAUTHORIZED: "يرجى تسجيل الدخول للمتابعة.",
  FORBIDDEN: "لا تملك صلاحية تنفيذ هذه العملية.",
  NOT_FOUND: "تعذر العثور على العنصر المطلوب.",
  VERCEL_BLOB_TOKEN_MISSING: "خدمة رفع الملفات غير مهيأة حاليًا.",
};

const internalValuePattern = /^[A-Z][A-Z0-9_]*$/;
const hasArabic = /[\u0600-\u06ff]/;

export function dashboardLabel(value: string | null | undefined, fallback = "غير محدد") {
  if (!value) return fallback;
  const normalized = value.trim();
  return dashboardValueLabels[normalized] || (internalValuePattern.test(normalized) ? fallback : normalized);
}

export function dashboardErrorMessage(value: unknown, fallback: string) {
  if (typeof value !== "string" || !value.trim()) return fallback;
  const normalized = value.trim();
  if (dashboardErrorLabels[normalized]) return dashboardErrorLabels[normalized];
  return hasArabic.test(normalized) ? normalized : fallback;
}

export function localizeDashboardDetails(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(localizeDashboardDetails);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item], index) => [dashboardFieldLabels[key] || `تفصيل إضافي ${index + 1}`, localizeDashboardDetails(item)]),
    );
  }
  if (typeof value === "string") return dashboardValueLabels[value] || (internalValuePattern.test(value) ? "غير محدد" : value);
  return value;
}
