"use client";
import { motion } from "framer-motion";
import { Eye,MonitorSmartphone,Gem,TrendingUp,Settings2,HandHeart } from "lucide-react";
import { Section,SectionHeading } from "@/components/site/section-primitives";
const icons=[Eye,MonitorSmartphone,Gem,TrendingUp,Settings2,HandHeart];
const ar=["تشخيص الوضع وترتيب الأولويات","مواقع ومتاجر ومنصات وأنظمة","التموضع والهوية والرسائل","خطط النمو والحملات ومسار العميل","تبسيط العمليات والأتمتة","مراجعة مستقلة قبل القرار"];
const en=["Diagnosis and priorities","Sites, stores, platforms and systems","Positioning, identity and messaging","Growth plans and customer journeys","Operations and automation","Independent review before a decision"];
type P={rtl:boolean;areas:{title:string;text:string}[]};
export function HowWeHelpAreas({rtl,areas}:P){const ex=rtl?ar:en;return <Section tone="muted" className="section-texture !pt-24 sm:!pt-28"><SectionHeading eyebrow={rtl?"أين نساعد":"Where we help"} title={rtl?"نساعدك حيث يحتاج مشروعك فعلًا":"We help where your business truly needs it"} intro={rtl?"قد تكون المشكلة في القرار أو الموقع أو النظام أو الهوية أو التسويق. نبدأ من أصل المشكلة ثم نختار ما يجب تحسينه أو بناؤه":"We begin with the root problem, then choose what should be improved or built"}/><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{areas.map((a,i)=>{const I=icons[i]||Eye;return <motion.div key={a.title} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} whileHover={{y:-4}} className="rounded-xl border border-border bg-background p-7 transition-all hover:border-camel/40 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-camel/10"><I className="h-5 w-5 text-accent"/></div><h3 className="mt-5 font-display text-xl font-medium text-ink">{a.title}</h3><p className="mt-3 text-base leading-relaxed text-muted-foreground">{a.text}</p><p className="mt-4 border-t border-border/70 pt-4 text-sm font-medium leading-relaxed text-ink/70">{ex[i]}</p></motion.div>})}</div></Section>;}
