export const launchCopy = {
  ar: {
    hero: {
      eyebrow: "سايبرويل",
      title1: "من حيث أنت…",
      title2: "إلى حيث تريد أن تكون",
      promise: "نساعد أصحاب الأعمال على فهم تحدياتهم الرقمية، واتخاذ القرار المناسب، وبناء الحل الذي يحتاجه مشروعهم فعلًا",
      execution: "من التشخيص والتخطيط والتحليل المالي إلى بناء المواقع والأنظمة والأتمتة وحماية أعمالك الرقمية",
      note: "لا عروض جاهزة، ولا حلول عشوائية، ولا هدر للوقت والمال",
      primary: "ابدأ محادثة الآن",
      secondary: "شاركنا مشكلتك",
      ctaNote: "أحيانًا لا تحتاج إلى تغيير كل شيء… فقط إلى فهم المشكلة واتخاذ الخطوة الصحيحة التالية",
    },
    situations: {
      eyebrow: "ابدأ من وضعك الحقيقي",
      title: "أيٌّ من هذه الحالات يشبهك؟",
      intro: "يكفي أن تعرف ما الذي يعيق تقدّمك",
      items: [
        ["لدي مشروع ولا أعرف الخطوة التالية", "نرتب الصورة ونحدد القرار الأكثر أولوية بدل تشتيتك بعشرات الخيارات"],
        ["لدي مشكلة رقمية ولا أعرف سببها", "نفصل الأعراض عن السبب الحقيقي قبل البدء بأي تنفيذ"],
        ["أحتاج موقعًا أو نظامًا لكن أخشى الاختيار الخطأ", "نحدد ما تحتاجه فعلًا، وما يمكنك تأجيله، وما لا يستحق أن تدفع مقابله الآن"],
      ],
    },
    process: {
      eyebrow: "ماذا نفعل فعليًا؟",
      title: "من المشكلة الغامضة إلى خطوة قابلة للتنفيذ",
      intro: "وضوح → قرار → تقدّم هي منهجيتنا. والخطوات الأربع التالية هي طريقتنا العملية لتطبيقها من الفهم حتى التنفيذ",
      items: [
        ["نوضح المشكلة", "نحدد موضع الخلل الحقيقي والنتيجة التي تريد الوصول إليها"],
        ["نحدد القرار", "نرتب الخيارات ونختار الخطوة الأعلى أثرًا والأقل هدرًا"],
        ["نبني الحل", "موقع، نظام، هوية أو خطة نمو عندما يكون ذلك هو الحل الصحيح"],
        ["نرافق التنفيذ", "نتابع معك خطوة بخطوة حتى يصبح التقدم واضحًا وملموسًا"],
      ],
    },
    areas: {
      eyebrow: "ماذا ننفّذ؟",
      title: "من القرار إلى الحل",
      intro: "من التحليل المالي والتخطيط إلى بناء المواقع والأنظمة والأتمتة وحماية الأعمال الرقمية",
      items: [
        ["تحليل وقرار", "نوضح الصورة ونرتب الأولويات قبل التنفيذ"],
        ["مواقع ومنصات", "نبني حضورًا ومنتجات رقمية تخدم هدفًا واضحًا"],
        ["أنظمة وأتمتة", "ننظم العمل ونربط الأدوات ونقلل الهدر"],
        ["أمن وتطوير", "نحمي ما تبنيه ونطوره مع نمو مشروعك"],
      ],
    },
    why: {
      eyebrow: "لماذا سايبرويل؟",
      title: "نحن لا نبيع الاستعجال، بل نبني الثقة",
      body: "قد لا تحتاج موقعًا جديدًا أو تسويقًا أكثر أو نظامًا أكبر. قد تحتاج أولًا إلى فهم أوضح أو خطوة أبسط. لن ندفعك نحو عمل لا تحتاجه",
      note: "CyberWeel — شريكك للتقدم، لا مجرد وكالة",
    },
    principles: {
      eyebrow: "كيف نفكر",
      title: "مبادئ تُوجّه كل قرار",
      intro: "أربعة مبادئ تحكم كل توصية وقرار وتنفيذ",
      items: [
        ["نبدأ من السؤال الحقيقي", "المشكلة المعلنة نادرًا ما تكون المشكلة الفعلية؛ نبحث أولًا عمّا تحاول حله حقًا"],
        ["نفضّل الخطوة الأبسط", "خطوة صغيرة مختارة جيدًا قد تتفوق على مشروع كبير لا يخدم الأولوية الحالية"],
        ["نقول ما نعتقده فعلًا", "الصدق قبل المجاملات؛ نسمي الثغرة ونقول الانتظار عندما يكون هو القرار الأنسب"],
        ["نصمّم لما يدوم", "نبني قرارات وأنظمة يتراكم أثرها بدل حلول سريعة تتبدد بعد فترة قصيرة"],
      ],
    },
    faq: {
      eyebrow: "أسئلة",
      title: "ما الذي تحتاج إلى معرفته قبل أن تبدأ؟",
      intro: "إجابات واضحة بلا لغة وكالات أو وعود مبالغ فيها",
      items: [
        ["هل سايبرويل وكالة رقمية؟", "لسنا وكالة بالمعنى التقليدي. نبدأ بالفهم والقرار، ثم ننفذ الموقع أو النظام أو الهوية عندما يكون ذلك هو الحل الصحيح"],
        ["ماذا يعني وضوح، قرار، تقدم؟", "هي منهجيتنا في العمل: نفهم الوضع الحقيقي، نختار الخطوة المناسبة، ثم نحولها إلى تقدم قابل للملاحظة. أما الخطوات الأربع فهي التطبيق العملي لهذه المنهجية"],
        ["هل تقبلون كل مشروع؟", "لا. قد تكون توصيتنا أن تؤجل التنفيذ أو تختار خطوة أبسط، ولن نقترح عليك عملًا لا تحتاجه"],
        ["مع من تعملون؟", "نعمل مع أصحاب الأعمال والمؤسسين والفرق التي تواجه قرارًا رقميًا أو تشغيليًا وتحتاج إلى رؤية أوضح"],
        ["كيف يبدأ التعاون؟", "بمحادثة قصيرة نفهم فيها وضعك وما يعيقك، ثم نحدد معك الخطوة التالية دون ضغط أو عرض جاهز"],
      ],
    },
    final: {
      title: "أخبرنا بما يعيقك",
      body: "وسنساعدك على تحديد الخطوة التالية، بوضوح ودون ضغط",
      primary: "ابدأ محادثة الآن",
      secondary: "شاركنا مشكلتك",
    },
  },
  en: {
    hero: {
      eyebrow: "CyberWeel",
      title1: "From where you are…",
      title2: "to where you want to be",
      promise: "We help business owners understand their digital challenges, make sound decisions, and build what their business genuinely needs.",
      execution: "From diagnosis, planning, and financial analysis to websites, business systems, automation, and cybersecurity.",
      note: "No prepackaged pitches. No random solutions. No wasted time or budget.",
      primary: "Start a conversation",
      secondary: "Share your challenge",
      ctaNote: "Sometimes you do not need to change everything. You only need to understand the problem and take the right next step.",
    },
    situations: {
      eyebrow: "Start with where you are",
      title: "Does any of this sound familiar?",
      intro: "You do not need all the answers. You only need to identify what is holding you back.",
      items: [
        ["I have a project, but no clear next step", "We bring the situation into focus and identify the decision that matters most."],
        ["I have a digital problem, but I do not know the cause", "We separate the visible symptoms from the underlying issue before any work begins."],
        ["I need a website or system, but I am worried about choosing badly", "We define what you need now, what can wait, and what is not worth paying for yet."],
      ],
    },
    process: {
      eyebrow: "How we work",
      title: "From an unclear problem to a practical next step",
      intro: "Clarity → Decision → Progress is our methodology. These four steps show how we apply it, from understanding the situation to delivering the solution.",
      items: [
        ["Clarify the problem", "We identify the real bottleneck and the outcome you are trying to reach."],
        ["Make the decision", "We weigh the options and choose the highest-impact step with the least waste."],
        ["Build the solution", "We design and deliver the website, system, automation, identity, or plan the situation actually calls for."],
        ["Carry it through", "We stay involved until the work is implemented and progress becomes visible and measurable."],
      ],
    },
    areas: {
      eyebrow: "What we deliver",
      title: "From decision to working solution",
      intro: "We combine strategic clarity with practical delivery across the areas that move a business forward.",
      items: [
        ["Analysis and decision support", "We clarify the situation, assess priorities, and define the right course before execution."],
        ["Websites and digital platforms", "We build websites, online stores, and digital products around a clear business objective."],
        ["Business systems and automation", "We organize operations, connect tools, automate repetitive work, and reduce avoidable waste."],
        ["Cybersecurity and improvement", "We protect what you build and strengthen it as your business grows."],
      ],
    },
    why: {
      eyebrow: "Why CyberWeel?",
      title: "We do not sell urgency. We build confidence.",
      body: "You may not need a new website, a bigger system, or more marketing. You may first need a clearer diagnosis or a simpler step. We will not push work that does not serve your real priority.",
      note: "CyberWeel — your partner in progress, not just another agency.",
    },
    principles: {
      eyebrow: "How we think",
      title: "Principles behind every recommendation",
      intro: "Four principles guide how we assess, recommend, and deliver.",
      items: [
        ["Start with the real question", "The stated problem is rarely the whole problem. We first uncover what you are actually trying to solve."],
        ["Prefer the simplest effective step", "A well-chosen small step can create more value than a large project aimed at the wrong priority."],
        ["Say what we genuinely believe", "Honesty comes before an easy sale. We name the gap and recommend waiting when waiting is the better decision."],
        ["Design for lasting value", "We build decisions, systems, and assets whose value grows over time instead of fading after a quick launch."],
      ],
    },
    faq: {
      eyebrow: "Frequently asked questions",
      title: "What should you know before we begin?",
      intro: "Straight answers, without agency jargon or inflated promises.",
      items: [
        ["Is CyberWeel a digital agency?", "Not in the traditional sense. We begin by understanding the situation and defining the right decision, then we design and deliver the solution when execution is the right next step."],
        ["What do clarity, decision, and progress mean?", "They describe how we work: understand the real situation, choose the right step, and turn it into visible progress. Our four-step process is the practical application of that methodology."],
        ["Do you accept every project?", "No. We may recommend delaying the work, reducing the scope, or taking a simpler step. We will not propose work you do not need."],
        ["Who do you work with?", "We work with business owners, founders, and teams facing an important digital or operational decision and looking for a clearer way forward."],
        ["How does working together begin?", "It starts with a focused conversation about your situation, what is getting in the way, and what the most useful next step could be."],
      ],
    },
    final: {
      title: "Tell us what is getting in the way",
      body: "We will help you identify the right next step—clearly, honestly, and without pressure.",
      primary: "Start a conversation",
      secondary: "Share your challenge",
    },
  },
} as const;
