"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { RefreshCw, Search } from "lucide-react";
import { AdminShell } from "@/components/admin/admin-shell";
import { DateText } from "@/components/ui/date-text";

type Log = { id: string; action: string; category: "POSITIVE" | "SENSITIVE" | "NORMAL"; entityType: string; entityId: string | null; entityLabel: string | null; before: string | number | boolean | null; after: string | number | boolean | null; createdAt: string; actor: { id: string; name: string | null; email: string } | null };
type Actor = { id: string; name: string | null; email: string };
const labels: Record<string, string> = { PARTNER_APPLICATION_SUBMITTED: "تقديم طلب شراكة", PARTNER_REVIEW_STARTED: "بدء مراجعة طلب", PARTNER_INFO_REQUESTED: "طلب معلومات إضافية", PARTNER_APPLICATION_ACCEPTED: "قبول طلب شراكة", PARTNER_APPLICATION_REJECTED: "رفض طلب شراكة", PARTNER_ACCOUNT_ACTIVATED: "تفعيل حساب شريك", PARTNER_ACCOUNT_SUSPENDED: "إيقاف حساب شريك", PARTNER_PROFILE_UPDATED: "تعديل بيانات شريك", PARTNER_NOTE_ADDED: "إضافة ملاحظة إدارية", PARTNER_PROJECT_ASSIGNED: "إسناد مشروع لشريك", PROJECT_CREATED: "إنشاء مشروع", ADMIN_PERMISSIONS_UPDATED: "تعديل صلاحيات إدارة" };
const styles = { POSITIVE: "border-emerald-200 bg-emerald-50", SENSITIVE: "border-rose-200 bg-rose-50", NORMAL: "border-sky-200 bg-sky-50" };

export default function AuditLogPage() {
  const router = useRouter();
  const [logs, setLogs] = useState<Log[]>([]); const [actors, setActors] = useState<Actor[]>([]); const [actions, setActions] = useState<string[]>([]); const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ q: "", actorId: "", action: "", category: "", from: "", to: "" });
  const load = useCallback(async () => { setLoading(true); const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); const response = await fetch(`/api/admin/audit-log?${query}`, { cache: "no-store" }); if (response.status === 401) return router.replace("/login"); const data = await response.json(); if (response.ok) { setLogs(data.logs); setActors(data.actors); setActions(data.actions); } setLoading(false); }, [filters, router]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  return <AdminShell active="audit-log" title="سجل النشاطات الإدارية" description="سجل زمني غير قابل للتعديل للعمليات المهمة والتغييرات الحساسة داخل لوحة الإدارة.">
    <section className="mt-7 rounded-2xl border border-[#D8D2C4] bg-white p-5 shadow-sm"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><label className="relative xl:col-span-2"><Search className="absolute right-3 top-3.5 h-4 w-4 text-slate-400" /><input value={filters.q} onChange={(e) => setFilters((v) => ({ ...v, q: e.target.value }))} placeholder="بحث بالعنصر أو المعرّف" className="field pr-10" /></label><select value={filters.actorId} onChange={(e) => setFilters((v) => ({ ...v, actorId: e.target.value }))} className="field"><option value="">كل المستخدمين</option>{actors.map((actor) => <option key={actor.id} value={actor.id}>{actor.name || actor.email}</option>)}</select><select value={filters.action} onChange={(e) => setFilters((v) => ({ ...v, action: e.target.value }))} className="field"><option value="">كل العمليات</option>{actions.map((action) => <option key={action} value={action}>{labels[action] || action}</option>)}</select><input type="date" value={filters.from} onChange={(e) => setFilters((v) => ({ ...v, from: e.target.value }))} className="field" /><input type="date" value={filters.to} onChange={(e) => setFilters((v) => ({ ...v, to: e.target.value }))} className="field" /></div><div className="mt-3 flex flex-wrap gap-2">{[["", "الكل"], ["POSITIVE", "إيجابية"], ["SENSITIVE", "حساسة"], ["NORMAL", "تعديلات عادية"]].map(([value, label]) => <button key={value} onClick={() => setFilters((v) => ({ ...v, category: value }))} className={`rounded-full px-4 py-2 text-sm font-black ${filters.category === value ? "bg-[#111827] text-white" : "bg-[#F7F3EB]"}`}>{label}</button>)}</div></section>
    <section className="mt-5 grid gap-3">{loading ? <p className="flex items-center justify-center gap-2 rounded-2xl bg-white p-10"><RefreshCw className="h-5 w-5 animate-spin" />جارٍ تحميل السجل...</p> : logs.length ? logs.map((log) => <article key={log.id} className={`rounded-2xl border p-5 ${styles[log.category]}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">{labels[log.action] || log.action}</h2><p className="mt-1 text-sm text-slate-600">{log.entityLabel || log.entityId || log.entityType} · بواسطة {log.actor?.name || log.actor?.email || "النظام"}</p></div><span className="text-sm font-bold"><DateText value={log.createdAt} withTime /></span></div>{(log.before || log.after) && <details className="mt-4 rounded-xl bg-white/70 p-3"><summary className="cursor-pointer font-bold">عرض القيم قبل وبعد</summary><div className="mt-3 grid gap-3 md:grid-cols-2"><pre className="overflow-auto whitespace-pre-wrap rounded-lg bg-white p-3 text-xs" dir="ltr">{JSON.stringify(log.before, null, 2) || "—"}</pre><pre className="overflow-auto whitespace-pre-wrap rounded-lg bg-white p-3 text-xs" dir="ltr">{JSON.stringify(log.after, null, 2) || "—"}</pre></div></details>}</article>) : <p className="rounded-2xl bg-white p-10 text-center text-slate-500">لا توجد نشاطات مطابقة للفلاتر.</p>}</section>
  </AdminShell>;
}
